boatd:
    port: 2222
    interface: 0.0.0.0

plugin_directory: null

plugins:
    - opencpn:
        enabled: true
        device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AD01UBXA-if00-port0
        baud: 9600
        destination_ip: 192.168.40.255

    - logger:
        enabled: false
        period: 1
        filename: /var/log/boatd/wrsc2019
    - gpx_logger:
        enabled: true
        period: 1
        filename: /var/log/boatd/wrsc2019-gpx

waypoint_file: '/home/pi/waypoints'

driver:
    file: /home/pi/dewi/dewi-boatd-driver/dewi_boatd_driver.py
    #module: dewi_boatd_driver


behaviours:
    - waypoint:
        file: looped-waypoint-behaviour
    - station-keeping:
        file: station-keeping-behaviour
    - idle:
        file: idle-behaviour

wind_filtering:       
    enabled: true
    rate_of_change: 75

