boatd:
    port: 2222
    interface: 0.0.0.0

plugin_directory: null

plugins:
    - mavlink:
        enabled: true
        device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AD01UBXA-if00-port0
        baud: 9600
    - logger:
        enabled: true
        period: 1
        filename: /var/log/boatd/aber-2018-06-30
    - gpx_logger:
        enabled: true
        period: 1
        filename: /var/log/boatd/aber-2018-06-30

waypoint_file: '/home/pi/aber-waypoints'

driver:
    #file: ~/git/sails-boatd-driver/driver.py
    module: dewi_boatd_driver


behaviours:
    - waypoint:
        file: looped-waypoint-behaviour
    - station-keeping:
        file: station-keeping-behaviour
    - idle:
        file: idle-behaviour

wind_filtering:       
    enabled: true
    rate_of_change: 75

